
<?php
  /*
    Copyright 2010 Persistent Systems Limited

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
   */

    /**
    * This code was generated by the tool 'PHPDataSvcUtil.php'.
    * Runtime Version:1.0
    *
    * Changes to this file may cause incorrect behavior and will be lost if
    * the code is regenerated.
    */

    require_once 'Context/ObjectContext.php';
    /**
    * Defines default OData Service URL for this proxy class
    */
    define("DEFAULT_ODATA_SERVICE_URL", "http://itelligencechina.vicp.cc:8008/sap/opu/odata/sap/Z_BAPI_PR_GETDETAIL_OFFICAL_SRV");
    
   /**
    * Container class Z_BAPI_PR_GETDETAIL_OFFICAL_SRV_Entities, Namespace: Z_BAPI_PR_GETDETAIL_OFFICAL_SRV
    */
    class Z_BAPI_PR_GETDETAIL_OFFICAL_SRV_Entities extends ObjectContext
    {
    
        protected $_RequisitionItemsSet;
        
       /**
        * The constructor for Z_BAPI_PR_GETDETAIL_OFFICAL_SRV_Entities accepting service URI
        */
        public function __construct($uri = "")
        {
            if(strlen($uri) == 0)
            {
                $uri = DEFAULT_ODATA_SERVICE_URL;
            }

            if (Utility::reverseFind($uri, '/') != strlen($uri) - 1)
            {
                $uri = $uri . '/';
            }

            $this->_baseURI = $uri;
            parent::__construct($this->_baseURI);
            $this->_entities = array(
                                "RequisitionItemsSet");
            $this->_entitySet2Type = array(
                                            "requisitionitemsset" => "RequisitionItems");
            $this->_entityType2Set = array(
                                            "requisitionitems" => "RequisitionItemsSet");

            $this->_association = array();

    
            $this->_RequisitionItemsSet = new DataServiceQuery('/'.'RequisitionItemsSet', $this);

        }

    
        /**
         * Function returns DataServiceQuery reference for
         * the entityset RequisitionItemsSet
         * @return DataServiceQuery
         */
        public function RequisitionItemsSet()
        {
            $this->_RequisitionItemsSet->ClearAllOptions();
            return $this->_RequisitionItemsSet;
        }
    
       /**
        * Functions for adding object to the entityset/collection
        */
    
       /**
        * Add RequisitionItemsSet
        * @param RequisitionItemsSet $object
        */
      public function AddToRequisitionItemsSet($object)
        {
            return parent::AddObject('RequisitionItemsSet', $object);
        }
    

       /**
        * This function returns the entities.
        */
        public function getEntities()
        {
            return $this->_entities;
        }
    }
  
   /**
    * @class:RequisitionItems
    * @type:EntityType
    * @key:PreqItem
    * @key:PreqNo
    */
    class RequisitionItems extends Object
    {
        protected $_entityMap = array();
        protected $_entityKey = array();
        protected $_relLinks  = array();
        protected $_baseURI;

    
       /**
        * @Type:EntityProperty
        * @EdmType:Edm.String
        * @MaxLength:10
        * @FixedLength:
        */
        public $BudgetPeriod;
    
       /**
        * @Type:EntityProperty
        * @EdmType:Edm.String
        * @MaxLength:20
        * @FixedLength:
        */
        public $FundLong;
    
       /**
        * @Type:EntityProperty
        * @EdmType:Edm.String
        * @MaxLength:20
        * @FixedLength:
        */
        public $GrantNbr;
    
       /**
        * @Type:EntityProperty
        * @EdmType:Edm.String
        * @MaxLength:16
        * @FixedLength:
        */
        public $FuncArea;
    
       /**
        * @Type:EntityProperty
        * @EdmType:Edm.String
        * @MaxLength:3
        * @FixedLength:
        */
        public $ResItem;
    
       /**
        * @Type:EntityProperty
        * @EdmType:Edm.String
        * @MaxLength:10
        * @FixedLength:
        */
        public $ResDoc;
    
       /**
        * @Type:EntityProperty
        * @EdmType:Edm.String
        * @MaxLength:10
        * @FixedLength:
        */
        public $Fund;
    
       /**
        * @Type:EntityProperty
        * @EdmType:Edm.String
        * @MaxLength:16
        * @FixedLength:
        */
        public $FundsCtr;
    
       /**
        * @Type:EntityProperty
        * @EdmType:Edm.String
        * @MaxLength:14
        * @FixedLength:
        */
        public $CmmtItem;
    
       /**
        * @Type:EntityProperty
        * @EdmType:Edm.String
        * @MaxLength:4
        * @FixedLength:
        */
        public $ProcuringPlant;
    
       /**
        * @Type:EntityProperty
        * @EdmType:Edm.String
        * @MaxLength:60
        * @FixedLength:
        */
        public $ReasonBlocking;
    
       /**
        * @Type:EntityProperty
        * @EdmType:Edm.String
        * @MaxLength:1
        * @FixedLength:
        */
        public $ReqBlocked;
    
       /**
        * @Type:EntityProperty
        * @EdmType:Edm.String
        * @MaxLength:10
        * @FixedLength:
        */
        public $PurMatVersion;
    
       /**
        * @Type:EntityProperty
        * @EdmType:Edm.String
        * @MaxLength:32
        * @FixedLength:
        */
        public $PurMatGuid;
    
       /**
        * @Type:EntityProperty
        * @EdmType:Edm.String
        * @MaxLength:40
        * @FixedLength:
        */
        public $PurMatExternal;
    
       /**
        * @Type:EntityProperty
        * @EdmType:Edm.String
        * @MaxLength:10
        * @FixedLength:
        */
        public $MaterialVersion;
    
       /**
        * @Type:EntityProperty
        * @EdmType:Edm.String
        * @MaxLength:32
        * @FixedLength:
        */
        public $MaterialGuid;
    
       /**
        * @Type:EntityProperty
        * @EdmType:Edm.String
        * @MaxLength:40
        * @FixedLength:
        */
        public $MaterialExternal;
    
       /**
        * @Type:EntityProperty
        * @EdmType:Edm.String
        * @MaxLength:1
        * @FixedLength:
        */
        public $GeneralRelease;
    
       /**
        * @Type:EntityProperty
        * @EdmType:Edm.String
        * @MaxLength:3
        * @FixedLength:
        */
        public $PoUnitIso;
    
       /**
        * @Type:EntityProperty
        * @EdmType:Edm.String
        * @MaxLength:3
        * @FixedLength:
        */
        public $PreqUnitIso;
    
       /**
        * @Type:EntityProperty
        * @EdmType:Edm.String
        * @MaxLength:1
        * @FixedLength:
        */
        public $ItemCatExt;
    
       /**
        * @Type:EntityProperty
        * @EdmType:Edm.String
        * @MaxLength:3
        * @FixedLength:
        */
        public $CurrencyIso;
    
       /**
        * @Type:EntityProperty
        * @EdmType:Edm.String
        * @MaxLength:1
        * @FixedLength:
        */
        public $DelDatcatExt;
    
       /**
        * @Type:EntityProperty
        * @EdmType:Edm.String
        * @MaxLength:10
        * @FixedLength:
        */
        public $MfrNoExt;
    
       /**
        * @Type:EntityProperty
        * @EdmType:Edm.String
        * @MaxLength:10
        * @FixedLength:
        */
        public $MfrNo;
    
       /**
        * @Type:EntityProperty
        * @EdmType:Edm.String
        * @MaxLength:40
        * @FixedLength:
        */
        public $ManuMat;
    
       /**
        * @Type:EntityProperty
        * @EdmType:Edm.String
        * @MaxLength:4
        * @FixedLength:
        */
        public $ManufProf;
    
       /**
        * @Type:EntityProperty
        * @EdmType:Edm.String
        * @MaxLength:5
        * @FixedLength:
        */
        public $Currency;
    
       /**
        * @Type:EntityProperty
        * @EdmType:Edm.Decimal
        */
        public $Ordered;
    
       /**
        * @Type:EntityProperty
        * @EdmType:Edm.String
        * @MaxLength:22
        * @FixedLength:
        */
        public $VendMat;
    
       /**
        * @Type:EntityProperty
        * @EdmType:Edm.String
        * @MaxLength:10
        * @FixedLength:
        */
        public $Batch;
    
       /**
        * @Type:EntityProperty
        * @EdmType:Edm.String
        * @MaxLength:10
        * @FixedLength:
        */
        public $Promotion;
    
       /**
        * @Type:EntityProperty
        * @EdmType:Edm.String
        * @MaxLength:18
        * @FixedLength:
        */
        public $IntObjNo;
    
       /**
        * @Type:EntityProperty
        * @EdmType:Edm.String
        * @MaxLength:1
        * @FixedLength:
        */
        public $PoPrice;
    
       /**
        * @Type:EntityProperty
        * @EdmType:Edm.String
        * @MaxLength:1
        * @FixedLength:
        */
        public $KanbanInd;
    
       /**
        * @Type:EntityProperty
        * @EdmType:Edm.String
        * @MaxLength:10
        * @FixedLength:
        */
        public $PckgNo;
    
       /**
        * @Type:EntityProperty
        * @EdmType:Edm.String
        * @MaxLength:2
        * @FixedLength:
        */
        public $RevLev;
    
       /**
        * @Type:EntityProperty
        * @EdmType:Edm.String
        * @MaxLength:3
        * @FixedLength:
        */
        public $PoUnit;
    
       /**
        * @Type:EntityProperty
        * @EdmType:Edm.String
        * @MaxLength:1
        * @FixedLength:
        */
        public $SpecStock;
    
       /**
        * @Type:EntityProperty
        * @EdmType:Edm.String
        * @MaxLength:10
        * @FixedLength:
        */
        public $ValType;
    
       /**
        * @Type:EntityProperty
        * @EdmType:Edm.Decimal
        */
        public $NoResub;
    
       /**
        * @Type:EntityProperty
        * @EdmType:Edm.Decimal
        */
        public $Resubmis;
    
       /**
        * @Type:EntityProperty
        * @EdmType:Edm.DateTime
        */
        public $LastResub;
    
       /**
        * @Type:EntityProperty
        * @EdmType:Edm.String
        * @MaxLength:8
        * @FixedLength:
        */
        public $BomexplNo;
    
       /**
        * @Type:EntityProperty
        * @EdmType:Edm.String
        * @MaxLength:3
        * @FixedLength:
        */
        public $MrpContr;
    
       /**
        * @Type:EntityProperty
        * @EdmType:Edm.String
        * @MaxLength:3
        * @FixedLength:
        */
        public $Quotarritm;
    
       /**
        * @Type:EntityProperty
        * @EdmType:Edm.String
        * @MaxLength:10
        * @FixedLength:
        */
        public $QuotaArr;
    
       /**
        * @Type:EntityProperty
        * @EdmType:Edm.String
        * @MaxLength:10
        * @FixedLength:
        */
        public $InfoRec;
    
       /**
        * @Type:EntityProperty
        * @EdmType:Edm.String
        * @MaxLength:5
        * @FixedLength:
        */
        public $AgmtItem;
    
       /**
        * @Type:EntityProperty
        * @EdmType:Edm.String
        * @MaxLength:10
        * @FixedLength:
        */
        public $Agreement;
    
       /**
        * @Type:EntityProperty
        * @EdmType:Edm.String
        * @MaxLength:4
        * @FixedLength:
        */
        public $PurchOrg;
    
       /**
        * @Type:EntityProperty
        * @EdmType:Edm.String
        * @MaxLength:10
        * @FixedLength:
        */
        public $FixedVend;
    
       /**
        * @Type:EntityProperty
        * @EdmType:Edm.String
        * @MaxLength:10
        * @FixedLength:
        */
        public $DesVendor;
    
       /**
        * @Type:EntityProperty
        * @EdmType:Edm.String
        * @MaxLength:1
        * @FixedLength:
        */
        public $IrInd;
    
       /**
        * @Type:EntityProperty
        * @EdmType:Edm.String
        * @MaxLength:1
        * @FixedLength:
        */
        public $GrNonVal;
    
       /**
        * @Type:EntityProperty
        * @EdmType:Edm.String
        * @MaxLength:1
        * @FixedLength:
        */
        public $GrInd;
    
       /**
        * @Type:EntityProperty
        * @EdmType:Edm.String
        * @MaxLength:1
        * @FixedLength:
        */
        public $PartInv;
    
       /**
        * @Type:EntityProperty
        * @EdmType:Edm.String
        * @MaxLength:1
        * @FixedLength:
        */
        public $Distrib;
    
       /**
        * @Type:EntityProperty
        * @EdmType:Edm.String
        * @MaxLength:1
        * @FixedLength:
        */
        public $Acctasscat;
    
       /**
        * @Type:EntityProperty
        * @EdmType:Edm.String
        * @MaxLength:1
        * @FixedLength:
        */
        public $ItemCat;
    
       /**
        * @Type:EntityProperty
        * @EdmType:Edm.Decimal
        */
        public $PriceUnit;
    
       /**
        * @Type:EntityProperty
        * @EdmType:Edm.Decimal
        */
        public $CAmtBapi;
    
       /**
        * @Type:EntityProperty
        * @EdmType:Edm.Decimal
        */
        public $GrPrTime;
    
       /**
        * @Type:EntityProperty
        * @EdmType:Edm.DateTime
        */
        public $RelDate;
    
       /**
        * @Type:EntityProperty
        * @EdmType:Edm.DateTime
        */
        public $DelivDate;
    
       /**
        * @Type:EntityProperty
        * @EdmType:Edm.String
        * @MaxLength:1
        * @FixedLength:
        */
        public $DelDatcat;
    
       /**
        * @Type:EntityProperty
        * @EdmType:Edm.String
        * @MaxLength:3
        * @FixedLength:
        */
        public $Unit;
    
       /**
        * @Type:EntityProperty
        * @EdmType:Edm.Decimal
        */
        public $Quantity;
    
       /**
        * @Type:EntityProperty
        * @EdmType:Edm.String
        * @MaxLength:4
        * @FixedLength:
        */
        public $SupplPlnt;
    
       /**
        * @Type:EntityProperty
        * @EdmType:Edm.String
        * @MaxLength:9
        * @FixedLength:
        */
        public $MatGrp;
    
       /**
        * @Type:EntityProperty
        * @EdmType:Edm.String
        * @MaxLength:10
        * @FixedLength:
        */
        public $Trackingno;
    
       /**
        * @Type:EntityProperty
        * @EdmType:Edm.String
        * @MaxLength:4
        * @FixedLength:
        */
        public $StoreLoc;
    
       /**
        * @Type:EntityProperty
        * @EdmType:Edm.String
        * @MaxLength:4
        * @FixedLength:
        */
        public $Plant;
    
       /**
        * @Type:EntityProperty
        * @EdmType:Edm.String
        * @MaxLength:18
        * @FixedLength:
        */
        public $PurMat;
    
       /**
        * @Type:EntityProperty
        * @EdmType:Edm.String
        * @MaxLength:18
        * @FixedLength:
        */
        public $Material;
    
       /**
        * @Type:EntityProperty
        * @EdmType:Edm.String
        * @MaxLength:40
        * @FixedLength:
        */
        public $ShortText;
    
       /**
        * @Type:EntityProperty
        * @EdmType:Edm.DateTime
        */
        public $PreqDate;
    
       /**
        * @Type:EntityProperty
        * @EdmType:Edm.String
        * @MaxLength:12
        * @FixedLength:
        */
        public $PreqName;
    
       /**
        * @Type:EntityProperty
        * @EdmType:Edm.String
        * @MaxLength:12
        * @FixedLength:
        */
        public $CreatedBy;
    
       /**
        * @Type:EntityProperty
        * @EdmType:Edm.String
        * @MaxLength:3
        * @FixedLength:
        */
        public $PurGroup;
    
       /**
        * @Type:EntityProperty
        * @EdmType:Edm.String
        * @MaxLength:4
        * @FixedLength:
        */
        public $DocType;
    
       /**
        * @Type:EntityProperty
        * NotNullable
        * @EdmType:Edm.String
        * @MaxLength:5
        * @FixedLength:
        */
        public $PreqItem;
    
       /**
        * @Type:EntityProperty
        * NotNullable
        * @EdmType:Edm.String
        * @MaxLength:10
        * @FixedLength:
        */
        public $PreqNo;
    

       /**
        * Function to create an instance of RequisitionItems
        * @param Edm.String $PreqItem
        * @param Edm.String $PreqNo
        */
        public static function CreateRequisitionItems(
            $PreqItem, 
            $PreqNo)
        {   
            $RequisitionItems = new RequisitionItems();
            $RequisitionItems->PreqItem = $PreqItem;
            $RequisitionItems->PreqNo = $PreqNo;
            return $RequisitionItems;
        }

       /**
        * Constructor for RequisitionItems
        */
        public function __construct($uri = "")
        {
            $this->_objectID = Guid::NewGuid();
            $this->_baseURI = $uri;
    
        }

       /**
        * overring getObjectID() functon of Object class
        */
        public function getObjectID()
        {
            return $this->_objectID;
        }

       /**
        * This function returns the entity keys of this entity.
        */
        public function getEntityKeys()
        {
            return $this->_entityKey;
        }

       /**
        * This function set the entity keys of this entity.
        */
        public function setEntityKeys($entityKey)
        {
            $this->_entityKey = $entityKey;
        }

       /**
        * This function returns the related links of this entity.
        */
        public function getRelatedLinks()
        {
            return $this->_relLinks;
        }

       /**
        * This function set the related links of this entity.
        */
        public function setRelatedLinks($relLinks)
        {
            $this->_relLinks = $relLinks;
        }

       /**
        * Function for getting Entity Type Name corrosponding to navigation Name
        */
        public function getActualEntityTypeName($key)
        {
            if (array_key_exists($key, $this->_entityMap))
            {
                return ($this->_entityMap[$key]);
            }
            return $key;
        }
    }
  
?>
  